services:
  # Contenedor para el Frontend (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true 
      - VITE_API_URL=http://localhost:8000/api
      - VITE_STORAGE_KEY=---
    restart: always
    networks:
      - prolecom_network
    depends_on:
      backend:
        condition: service_started

  # Contenedor para el Backend (PHP + Apache)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_CONNECTION=--
      - DB_HOST=--
      - DB_PORT=--
      - DB_DATABASE=--
      - DB_USERNAME=--
      - DB_PASSWORD=--
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=---
    restart: always
    networks:
      - prolecom_network
    depends_on:
      db:
        condition: service_healthy

  # Contenedor para la Base de Datos (MySQL)
  db:
    image: mysql:8.0
    ports:
      - "3307:3306" 
    environment:
      MYSQL_DATABASE: prolecom
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/scripts:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - prolecom_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Herramienta de gestión de base de datos
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - prolecom_network

networks:
  prolecom_network:
    driver: bridge

volumes:
  db_data:

 