# SonarQube Project Configuration
sonar.projectKey=T3-Prolecom
sonar.projectName=T3-Prolecom
sonar.projectVersion=1.0
sonar.organization=Sebastian

# Paths to the source directories
sonar.sources=backend,frontend

# Exclude directories
sonar.exclusions=**/node_modules/**, **/vendor/**, **/tests/**

# Languages
sonar.language=php,js

# Backend specific
sonar.php.tests.reportPath=backend/build/logs/clover.xml
sonar.php.coverage.reportPath=backend/build/logs/clover.xml

# Frontend specific
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.eslint.reportPaths=frontend/eslint-report.json
